'use server';
// Property assignment, NOT destructuring — destructuring these exports breaks the Next build.
import { defineResource, action } from './registry';
import { moveTask } from '@/app/_lib/store';
import type { Task } from '@/types';

const tasks = defineResource<Task>()({
  table: 'tasks',
  scope: { column: 'owner_id' },
  writableFields: ['title', 'done'],
  actions: { list: true, create: true, update: true, remove: true },
  revalidate: 'tasks',
});

export const list = tasks.list;
export const create = tasks.create;
export const update = tasks.update;
export const remove = tasks.remove;

// Bespoke actions aren't generated by defineResource, so they don't get IdInput/IdKey for free —
// accept the row too by hand, matching the generated CRUD above.
const resolveId = (idOrTask: Task | string): string => (typeof idOrTask === 'string' ? idOrTask : idOrTask.id);

// moveTask() scopes the swap to ctx.userId's own rows — see store.ts.
export const moveUp = action(
  async (ctx, idOrTask: Task | string) => moveTask(ctx.userId, resolveId(idOrTask), 'up'),
  { revalidate: 'tasks', name: 'tasks.moveUp' },
);
export const moveDown = action(
  async (ctx, idOrTask: Task | string) => moveTask(ctx.userId, resolveId(idOrTask), 'down'),
  { revalidate: 'tasks', name: 'tasks.moveDown' },
);
